version: '3'
services:
        web:
                build: .
                ports:
                        - "8069:8086"
                volumes:
                        - ./volumes:/volumes
                restart: unless-stopped
